FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
RUN npm install && npm install -g nodemon
COPY src ./src
RUN ls -a

EXPOSE 4002

CMD [ "npm", "run", "dev" ]
